### ISSUE TITLE
[Question] node_modules handling in Azure Function deployment

### ISSUE THREAD

**Issue by ipatalas** [shladdergoo/insult-function-azure#1]
Hi,

many thanks for [this wiki](https://github.com/shladdergoo/insult-function-azure/wiki/Debugging-Typescript-Azure-Functions-with-VS-Code) article. It helped me a lot with introducing TS to one of my AF functions. Azure Pipelines also did the job with deploying the app. However since it's zip deployed it has to contain all used **node_modules** which are not included in **postbuild** copy operation now.
I know I can just add them there, but I wonder how do you handle that?
I see basically two options:
- copy node_modules (may be slow when having a lot of files, altough I'm trying not to overuse npm packages)
- use webpack and bundle all dependencies into the functions

Any thoughts?

**Comment by shladdergoo** [comment]
Hi, sorry for being so long in replying. I use the 'Azure App Service Deploy' task in an Azure DevOps Release Pipeline (passing the zip that gets built in the Build pipeline). Within this task I specify a Post Deployment Action of 'npm install --only=prod' to ensure that the required dependencies are downloaded based on package.json (note the --only=prod means that only the runtime dependencies are downloaded, not the dev tooling)
